apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    application: MibWiki
spec:
  replicas: 1
  selector:
    matchLabels:
      application: MibWiki
      component: mysql
  serviceName: mysql
  template:
    metadata:
      name: mysql
      labels:
        application: MibWiki
        component: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: lkm98jvsjsd;ue
            - name: MYSQL_USER
              value: mibs
            - name: MYSQL_PASSWORD
              value: MarblesFound?
            - name: MYSQL_DATABASE
              value: mib_wiki
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: managed-premium
        resources:
          requests:            
            storage: 20Gi
