apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    application: MibWiki
    component: mysql
spec:
  selector:
    application: MibWiki
    component: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
