apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:    
    application: MibWiki
data:
  docker.cnf: |
    [mysqld]
    skip-host-cache
    skip-name-resolve
    default_authentication_plugin=mysql_native_password

